(function(){'use strict';var Jsonp={_attachScript:function(url,errorCallback){var script=new CKEDITOR.dom.element('script');script.setAttribute('src',url);script.on('error',errorCallback);CKEDITOR.document.getBody().append(script);return script;},sendRequest:function(urlTemplate,urlParams,callback,errorCallback){var request={};urlParams=urlParams||{};var callbackKey=CKEDITOR.tools.getNextNumber(),scriptElement;urlParams.callback='CKEDITOR._.jsonpCallbacks['+callbackKey+']';CKEDITOR._.jsonpCallbacks[callbackKey]=function(response){setTimeout(function(){cleanUp();callback(response);});};scriptElement=this._attachScript(urlTemplate.output(urlParams),function(){cleanUp();errorCallback&&errorCallback();});request.cancel=cleanUp;function cleanUp(){if(scriptElement){scriptElement.remove();delete CKEDITOR._.jsonpCallbacks[callbackKey];scriptElement=null;}}
return request;}};CKEDITOR.plugins.add('embedbase',{lang:'az,ca,cs,da,de,de-ch,en,eo,es,eu,fr,gl,id,it,ja,ko,ku,nb,nl,oc,pl,pt,pt-br,ru,sv,tr,ug,uk,zh,zh-cn',requires:'widget,notificationaggregator',onLoad:function(){CKEDITOR._.jsonpCallbacks={};},init:function(){CKEDITOR.dialog.add('embedBase',this.path+'dialogs/embedbase.js');}});function createWidgetBaseDefinition(editor){var aggregator,lang=editor.lang.embedbase;return{mask:true,template:'<div></div>',pathName:lang.pathName,_cache:{},urlRegExp:/^((https?:)?\/\/|www\.)/i,init:function(){this.on('sendRequest',function(evt){this._sendRequest(evt.data);},this,null,999);this.on('dialog',function(evt){evt.data.widget=this;},this);this.on('handleResponse',function(evt){if(evt.data.html){return;}
var retHtml=this._responseToHtml(evt.data.url,evt.data.response);if(retHtml!==null){evt.data.html=retHtml;}else{evt.data.errorMessage='unsupportedUrl';evt.cancel();}},this,null,999);},loadContent:function(url,opts){opts=opts||{};var that=this,cachedResponse=this._getCachedResponse(url),request={noNotifications:opts.noNotifications,url:url,callback:finishLoading,errorCallback:function(msg){that._handleError(request,msg);if(opts.errorCallback){opts.errorCallback(msg);}}};if(cachedResponse){setTimeout(function(){finishLoading(cachedResponse);});return;}
if(!opts.noNotifications){request.task=this._createTask();}
this.fire('sendRequest',request);function finishLoading(response){request.response=response;if(!that.editor.widgets.instances[that.id]){CKEDITOR.warn('embedbase-widget-invalid');if(request.task){request.task.done();}
return;}
if(that._handleResponse(request)){that._cacheResponse(url,response);if(opts.callback){opts.callback();}}}
return request;},isUrlValid:function(url){return this.urlRegExp.test(url)&&this.fire('validateUrl',url)!==false;},getErrorMessage:function(messageTypeOrMessage,url,suffix){var message=editor.lang.embedbase[messageTypeOrMessage+(suffix||'')];if(!message){message=messageTypeOrMessage;}
return new CKEDITOR.template(message).output({url:url||''});},_sendRequest:function(request){var that=this,jsonpRequest=Jsonp.sendRequest(this.providerUrl,{url:encodeURIComponent(request.url)},request.callback,function(){request.errorCallback('fetchingFailed');});request.cancel=function(){jsonpRequest.cancel();that.fire('requestCanceled',request);};},_handleResponse:function(request){var evtData={url:request.url,html:'',response:request.response};if(this.fire('handleResponse',evtData)!==false){if(request.task){request.task.done();}
this._setContent(request.url,evtData.html);return true;}else{request.errorCallback(evtData.errorMessage);return false;}},_handleError:function(request,messageTypeOrMessage){if(request.task){request.task.cancel();if(!request.noNotifications){editor.showNotification(this.getErrorMessage(messageTypeOrMessage,request.url),'warning');}}},_responseToHtml:function(url,response){if(response.type=='photo'){return '<img src="'+CKEDITOR.tools.htmlEncodeAttr(response.url)+'" '+
'alt="'+CKEDITOR.tools.htmlEncodeAttr(response.title||'')+'" style="max-width:100%;height:auto" />';}else if(response.type=='video'||response.type=='rich'){response.html=response.html.replace(/<iframe/g,'<iframe tabindex="-1"');return response.html;}
return null;},_setContent:function(url,content){this.setData('url',url);this.element.setHtml(content);},_createTask:function(){if(!aggregator||aggregator.isFinished()){aggregator=new CKEDITOR.plugins.notificationAggregator(editor,lang.fetchingMany,lang.fetchingOne);aggregator.on('finished',function(){aggregator.notification.hide();});}
return aggregator.createTask();},_cacheResponse:function(url,response){this._cache[url]=response;},_getCachedResponse:function(url){return this._cache[url];}};}
CKEDITOR.plugins.embedBase={createWidgetBaseDefinition:createWidgetBaseDefinition,_jsonp:Jsonp};})();